---
title: "functions"
author: "DM"
format: html
---

## Functions

```{r}
library(roxygen2)
```


```{r}
airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
celsius4 <- (airtemps[4]-32)*5/9
```

```{r}
#' Convert  temperatures from Farenheit to Celsius
#' 
#' @param fahr Temp in degrees F to be converted
#' @return temperature in degrees Celsius
#' @export
#' @examples
#' fahr_to_celsius(32)
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}

celsius4 <- fahr_to_celsius(airtemps[1])
```

```{r}
celsius1 == celsius4
```

```{r}
celsius <- fahr_to_celsius(airtemps)
celsius
```

```{r}
celsius_to_fahr <- function(celsius) {
  fahr <- (celsius*9/5) + 32
  return(fahr)
}
```

```{r}
fahr <- celsius_to_fahr(celsius)
fahr

airtemps == fahr
```

# Exploring time saving functions

```{r}
convert_temps <- function(fahr) {
  celsius <- (fahr-32)*5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps( seq(-100, 100, 10)))

View(temps_df)
```



# Custom themes

```{r}
custom_theme <- function() {
  ggplot2::theme(
    text = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = 6),
    plot.title = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold')
    
  )
}


```




```{r}
library(ggplot2)

ggplot(temps_df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point() +
    custom_theme()
```

